Repository userdive/agent.js, pull requests merged in 2018-05, with the labels that each got.

#516 Docs/reference
  .textlintrc.js
  docs/command-queue.md
  docs/field-reference.md
  docs/getting-started.md
  website/i18n/en.json
  website/sidebars.json
  website/siteConfig.js
Labels: QA

#524 fix docs
  docs/command-queue.md
Labels: QA

#536 tweak document
  docs/command-queue.md
  docs/field-reference.md
Labels: in progress

#522 add e2e test runtime
  .circleci/config.yml
  .dockerignore
  Dockerfile
  examples/nightwatch.json
  examples/package.json
  yarn.lock
Labels: in progress

#540 リンクとテーブルの色変更
  website/static/css/custom.css
Labels: in progress

#553 reduce sauce device in ci
  browser-providers.conf.ts
Labels: QA

#554 Update Google Chrome version
  Dockerfile
Labels: enhancement, in progress

#562 update selenium-server using nightwatch
  examples/nightwatch.json
Labels: QA

#564 Refactor examples
  examples/built-in/index.pug
  examples/index.pug
  examples/nightwatch.json
  examples/package.json
  examples/plugin-create/index.pug
  examples/plugin-linker/index.pug
  examples/simple/cd-with-send.pug
  examples/simple/cd-with-set.pug
  examples/simple/index.pug
  examples/simple/multiple.pug
  examples/webpack.config.ts
  examples/with-angular/index.pug
  examples/with-angular1/index.pug
  examples/with-google-tag-manager/index.pug
  examples/with-react/index.pug
  examples/with-vue/index.pug
  package.json
Labels: QA

#567 add standard feature example
  .github/PULL_REQUEST_TEMPLATE.md
  examples/index.pug
  examples/simple/events.pug
  karma.conf.ts
  package.json
  yarn.lock
Labels: QA

#440 feat(packages/kaizenplatform) Added integration
  package.json
  packages/kaizenplatform/README.md
  packages/kaizenplatform/package.json
  packages/kaizenplatform/src/index.ts
  packages/kaizenplatform/src/plugin.ts
  packages/kaizenplatform/test/index.test.ts
  packages/kaizenplatform/test/kzs.test.ts
  packages/kaizenplatform/tsconfig.json
  packages/userdive/src/types.ts
  webpack.config.ts
Labels: QA, enhancement

#587 ignore domains not mandatory service from no-dead-link lint
  .textlintrc.js
Labels: in progress

#574 add linker docs
  docs/linker-plugin.md
  website/i18n/en.json
  website/sidebars.json
Labels: QA

#597 tuning for saucelabs CI
  karma.conf.ts
Labels: QA

#599 fix v1.1.0 release docs
  CHANGELOG.md
  README.md
Labels: QA
