Repository userdive/agent.js, pull requests merged in 2018-02, with the labels that each got.

#242 fix(packages/agent) cleanup send custom variables
  lerna.json
  package.json
  packages/agent/package.json
  packages/agent/src/core.ts
  packages/agent/src/logger.ts
  packages/agent/src/store.ts
  packages/agent/test/store.test.ts
  webpack.config.ts
Labels: enhancement, in progress

#244 fix(package) remove unused cdn files
  package.json
Labels: bug, in progress

#201 feat(website) use docusaurus
  .stylelintrc.json
  .yarnrc
  crowdin.yaml
  lerna.json
  package.json
  packages/agent/.npmignore
  website/.eslintrc.json
  website/.gitignore
  website/.yarnclean
  website/README.md
  website/blog/.gitkeep
  website/core/Footer.js
  website/i18n/en.json
  website/languages.js
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/img/favicon/favicon.ico
  yarn.lock
Labels: QA

#215 feat(examples) Merge userdive/examples into master
  .editorconfig
  .gitignore
  .pug-lintrc.json
  examples/README.md
  examples/index.pug
  examples/simple/multiple.pug
  examples/simple/simple.pug
  examples/simple/simple.test.ts
  examples/tsconfig.json
  examples/tslint.json
  examples/webpack.config.ts
  examples/with-angular/app.component.ts
  examples/with-angular/app.module.ts
  examples/with-angular/app.routing.ts
  examples/with-angular/components/sample1.component.ts
  examples/with-angular/components/sample2.component.ts
  examples/with-angular/index.pug
  examples/with-angular/main.test.ts
  examples/with-angular/main.ts
  examples/with-angular/package.json
  examples/with-angular1/controllers/sample1.ts
  examples/with-angular1/controllers/sample2.ts
  examples/with-angular1/index.pug
  examples/with-angular1/main.test.ts
  examples/with-angular1/main.ts
  examples/with-angular1/package.json
  examples/with-angular1/sample1.pug
  examples/with-angular1/sample2.pug
  examples/with-google-tag-manager/index.pug
  examples/with-react/components/Sample.tsx
  examples/with-react/components/sample1.tsx
  examples/with-react/components/sample2.tsx
  examples/with-react/index.pug
  examples/with-react/package.json
  examples/with-react/pages/Routes.tsx
  examples/with-react/pages/index.test.ts
  examples/with-react/pages/index.tsx
  examples/with-vue/index.pug
  examples/with-vue/index.test.ts
  examples/with-vue/index.ts
  examples/with-vue/package.json
  nightwatch.json
  package.json
  protractor.conf.js
  tslint.json
  yarn.lock
Labels: QA

#252 Fixed publish
  .travis.yml
  examples/simple/package.json
  examples/with-google-tag-manager/package.json
  package.json
  packages/agent/package.json
  scripts/publish
  yarn.lock
Labels: bug, in progress

#253 Release v0.12.0
  examples/simple/package.json
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-google-tag-manager/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  packages/agent/package.json
  website/package.json
Labels: in progress

#261 publish script mode change to 755
  lerna.json
  packages/agent/package.json
  scripts/publish
Labels: in progress

#285 chore(travis) Added workflow
  .travis.yml
Labels: in progress
