Repository userdive/agent.js, pull requests merged in 2018-03, with the labels that each got.

#294 add linker example
  examples/linker/linker.pug
  examples/linker/package.json
Labels: in progress

#302 Release v0.13.0
  .gitignore
  CHANGELOG.md
  examples/linker/package.json
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  lerna.json
  package.json
  packages/agent/package.json
  packages/linker/package.json
  website/package.json
  yarn.lock
Labels: in progress

#300 feat(packages) Merge userdive.js
  .travis.yml
  README.md
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  package.json
  packages/linker/package.json
  packages/userdive/LICENSE
  packages/userdive/README.md
  packages/userdive/karma.conf.ts
  packages/userdive/package.json
  packages/userdive/src/index.ts
  packages/userdive/test/index.test.ts
  packages/userdive/tsconfig.json
  yarn.lock
Labels: QA

#304 feat(docs) Added getting started
  .textlintrc.js
  docs/custom-variables.md
  docs/getting-started.md
  package.json
  website/i18n/en.json
  yarn.lock
Labels: enhancement, in progress

#317 refactor(travis) skip sauce when push
  .travis.yml
Labels: in progress

#319 chore(package) set v0.14.0-beta1
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  packages/agent/package.json
  packages/linker/package.json
  packages/userdive/package.json
  website/package.json
Labels: in progress

#303 Fixed linker lifecycle
  .travis.yml
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  package.json
  packages/agent/package.json
  packages/agent/src/agent.ts
  packages/agent/src/constants.ts
  packages/agent/src/core.ts
  packages/agent/src/entrypoint/debug.ts
  packages/agent/src/events.ts
  packages/agent/src/requests.ts
  packages/agent/src/store.ts
  packages/agent/src/types.ts
  packages/agent/test/agent.test.ts
  packages/agent/test/core.test.ts
  packages/agent/test/global.test.ts
  packages/linker/package.json
  packages/linker/src/handler.ts
  packages/linker/src/linker.ts
  packages/linker/test/handler.test.ts
  packages/linker/test/linker.test.ts
  packages/userdive/package.json
  tsconfig.json
  website/package.json
  yarn.lock
Labels: QA, bug

#326 fix(packages/agent) fix core scope
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  package.json
  packages/agent/package.json
  packages/agent/src/agent.ts
  packages/agent/test/agent.test.ts
  packages/linker/package.json
  packages/linker/src/linker.ts
  packages/userdive/package.json
  website/package.json
  yarn.lock
Labels: bug, in progress

#328 nightwatch
  .gitignore
  examples/nightwatch.base.json
  examples/with-angular/main.test.ts
  examples/with-angular/nightwatch.conf.js
  examples/with-angular/package.json
  examples/with-angular/tsconfig.json
  examples/with-angular1/main.test.ts
  examples/with-angular1/nightwatch.conf.js
  examples/with-angular1/package.json
  examples/with-angular1/tsconfig.json
  examples/with-react/nightwatch.conf.js
  examples/with-react/package.json
  examples/with-react/pages/index.test.ts
  examples/with-react/tsconfig.json
  examples/with-vue/index.test.ts
  examples/with-vue/nightwatch.conf.js
  examples/with-vue/package.json
  examples/with-vue/tsconfig.json
  package.json
  yarn.lock
Labels: enhancement, in progress

#329 refactor(examples) use es2015
  examples/with-angular/tsconfig.json
  examples/with-angular1/tsconfig.json
  examples/with-react/tsconfig.json
  examples/with-vue/tsconfig.json
Labels: QA, bug

#332 fix(renovate) Added examples
  renovate.json
Labels: QA

#334 fix(renovate) Added examples
  renovate.json
Labels: in progress

#340 Added developer document design
  website/pages/en/index.js
  website/siteConfig.js
  website/static/css/custom.css
  website/static/img/logo.svg
  website/static/img/logo_horizontal_white.png
  website/static/img/pic01.png
  website/static/img/pic02.png
Labels: in progress

#349 feat(appveyor) Actiate
  README.md
  appveyor.yml
  karma.conf.base.ts
  package.json
  yarn.lock
Labels: in progress

#348 feat(docs) Added outline spec
  .textlintrc.js
  docs/custom-variables.md
  docs/getting-started.md
  docs/integrations.md
  docs/plugins.md
  website/i18n/en.json
  website/languages.js
  website/package.json
  website/pages/en/index.js
  website/sidebars.json
  website/siteConfig.js
Labels: QA

#352 Release v0.14.0
  .textlintrc.js
  CHANGELOG.md
  LICENSE
  README.md
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  lint-staged.config.js
  package.json
  packages/agent/README.md
  packages/agent/package.json
  packages/linker/README.md
  packages/linker/package.json
  packages/userdive/README.md
  packages/userdive/package.json
  website/package.json
Labels: QA

#355 fix(scripts) Added author
  scripts/publish
Labels: QA

#357 feat(.circleci) Added e2e tests
  .circleci/config.yml
  .gitignore
  examples/.yarnclean
  examples/README.md
  examples/nightwatch.base.json
  examples/nightwatch.json
  examples/package.json
  examples/simple/simple.test.ts
  examples/spa-base.test.ts
  examples/tsconfig.json
  examples/tslint.json
  examples/with-angular/main.test.ts
  examples/with-angular/nightwatch.conf.js
  examples/with-angular/package.json
  examples/with-angular/tsconfig.json
  examples/with-angular/with-angular.test.ts
  examples/with-angular1/main.test.ts
  examples/with-angular1/package.json
  examples/with-angular1/tsconfig.json
  examples/with-angular1/with-angular1.test.ts
  examples/with-react/nightwatch.conf.js
  examples/with-react/package.json
  examples/with-react/pages/index.test.ts
  examples/with-react/pages/with-react.test.ts
  examples/with-react/tsconfig.json
  examples/with-vue/index.test.ts
  examples/with-vue/nightwatch.conf.js
  examples/with-vue/package.json
  examples/with-vue/tsconfig.json
  examples/with-vue/with-view.test.ts
  package.json
  website/i18n/en.json
  yarn.lock
Labels: QA

#354 add developers site
  .travis.yml
Labels: in progress

#365 refactor(website) Added simple spec
  .travis.yml
  lint-staged.config.js
  website/README.md
  website/core/Footer.js
  website/i18n/en.json
  website/package.json
  website/pages/en/index.js
  website/siteConfig.js
  website/static/img/classic.png
Labels: QA, enhancement

#366 Fix e2e test
  .circleci/config.yml
  examples/package.json
  examples/spa-base.test.ts
  examples/with-angular/index.pug
  examples/with-angular/with-angular.test.ts
  examples/with-angular1/index.pug
  examples/with-angular1/with-angular1.test.ts
  examples/with-react/components/Sample.tsx
  examples/with-react/components/sample1.tsx
  examples/with-react/components/sample2.tsx
  examples/with-react/index.pug
  examples/with-react/pages/index.tsx
  examples/with-react/pages/with-react.test.ts
  examples/with-vue/with-vue.test.ts
Labels: QA, bug

#367 refactor(packages/userdive) export namespace
  lint-staged.config.js
  packages/userdive/karma.conf.ts
  packages/userdive/src/index.ts
  packages/userdive/test/index.test.ts
Labels: QA

#368 refactor(packages/linker) Skip same origin
  package.json
  packages/linker/karma.conf.ts
  packages/linker/src/handler.ts
  packages/linker/src/linker.ts
  packages/linker/src/provide.ts
  packages/linker/test/handler.test.ts
  packages/linker/test/helpers/dom.ts
  packages/linker/test/linker.test.ts
  packages/linker/test/provide.test.ts
  yarn.lock
Labels: bug, in progress

#373 Release v0.15.0
  CHANGELOG.md
  examples/package.json
  examples/simple/package.json
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  packages/agent/package.json
  packages/linker/package.json
  packages/userdive/package.json
  website/package.json
Labels: QA

#378 add linker usage and badge to README. And tweak example.
  README.md
  examples/linker/linker.pug
  packages/linker/README.md
Labels: QA

#297 [breaking changes] fix(packages) create global entrypoint
  .circleci/config.yml
  .travis.yml
  examples/built-in/.yarnclean
  examples/built-in/README.md
  examples/built-in/index.pug
  examples/built-in/index.ts
  examples/built-in/package.json
  examples/index.pug
  examples/linker/linker.pug
  examples/package.json
  examples/webpack.config.ts
  package.json
  packages/agent/README.md
  packages/agent/src/agent.ts
  packages/agent/src/constants.ts
  packages/agent/src/core.ts
  packages/agent/src/entrypoint/debug.ts
  packages/agent/src/executer.ts
  packages/agent/src/global.ts
  packages/agent/src/types.ts
  packages/agent/test/agent.test.ts
  packages/agent/test/executer.test.ts
  packages/agent/test/global.test.ts
  packages/agent/test/helpers/plugin.ts
  packages/linker/README.md
  tslint.json
  webpack.config.ts
  website/package.json
  yarn.lock
Labels: QA, bug

#386 Release v1.0.0-beta1
  examples/built-in/package.json
  examples/linker/package.json
  examples/package.json
  examples/with-react/package.json
  lerna.json
  packages/agent/package.json
  packages/agent/src/global.ts
  packages/linker/package.json
  website/package.json
Labels: QA

#388 watch pug in examples
  examples/package.json
  package.json
Labels: QA

#389 fix(packages/agent) create queue first
  examples/built-in/package.json
  examples/linker/package.json
  examples/package.json
  examples/with-react/package.json
  lerna.json
  packages/agent/package.json
  packages/agent/src/agent.ts
  packages/agent/src/constants.ts
  packages/agent/src/core.ts
  packages/agent/src/entrypoint/debug.ts
  packages/agent/src/global.ts
  packages/agent/src/logger.ts
  packages/agent/src/types.ts
  packages/agent/test/global.test.ts
  packages/agent/test/logger.test.ts
  packages/linker/package.json
  website/package.json
Labels: QA, bug

#390 Re design example froms
  examples/index.pug
Labels: in progress

#392 chore(website) insert Google Tag manager
  website/core/Footer.js
  website/siteConfig.js
Labels: QA

#391 add docs of plugin
  docs/plugins.md
Labels: in progress

#364 send event
  docs/event.md
  examples/built-in/package.json
  examples/linker/package.json
  examples/package.json
  examples/with-react/package.json
  lerna.json
  packages/agent/README.md
  packages/agent/package.json
  packages/agent/src/agent.ts
  packages/agent/src/constants.ts
  packages/agent/src/core.ts
  packages/agent/src/global.ts
  packages/agent/src/types.ts
  packages/agent/test/core.test.ts
  packages/linker/package.json
  website/i18n/en.json
  website/package.json
  website/sidebars.json
Labels: enhancement, in progress

#383 refactor(packages) Update spec
  .circleci/config.yml
  .travis.yml
  README.md
  examples/index.pug
  examples/linker/linker.pug
  examples/package.json
  examples/spa-base.test.ts
  examples/with-angular1/nightwatch.conf.js
  examples/with-angular1/sample1.pug
  examples/with-angular1/sample2.pug
  examples/with-react/components/EntryPointWrapper.tsx
  examples/with-react/components/Sample.tsx
  examples/with-react/components/sample1.tsx
  examples/with-react/components/sample2.tsx
  examples/with-react/pages/Routes.tsx
  examples/with-react/pages/index.tsx
  package.json
  packages/agent/README.md
  packages/linker/README.md
  packages/userdive/README.md
  robots.txt
  website/siteConfig.js
  yarn.lock
Labels: QA

#404 fix(packages) Added global entrypoint type
  .circleci/config.yml
  packages/agent/package.json
  packages/agent/src/agent.ts
  packages/agent/src/constants.ts
  packages/agent/src/core.ts
  packages/agent/src/types.ts
  packages/agent/test/agent.test.ts
  packages/agent/test/core.test.ts
  packages/linker/src/provide.ts
  packages/userdive/src/index.ts
  packages/userdive/src/types.ts
  tsconfig.json
Labels: bug, enhancement, in progress

#410 fix(website) header logos
  website/static/css/custom.css
Labels: in progress

#422 Run e2e cron test
  .circleci/config.yml
  .travis.yml
  crowdin.yaml
  package.json
  website/languages.js
Labels: QA

#425 fix(packages/agent) fix send pageview default
  packages/agent/src/agent.ts
  packages/agent/src/global.ts
Labels: QA, bug

#424 fix(packages/agent) Added lazy queue
  .travis.yml
  examples/built-in/package.json
  examples/linker/package.json
  examples/package.json
  examples/simple/package.json
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  karma.conf.ts
  lerna.json
  package.json
  packages/agent/README.md
  packages/agent/package.json
  packages/agent/src/agent.ts
  packages/agent/src/browser.ts
  packages/agent/src/core.ts
  packages/agent/src/entrypoint/debug.ts
  packages/agent/src/entrypoint/index.ts
  packages/agent/src/global.ts
  packages/agent/src/logger.ts
  packages/agent/test/agent.test.ts
  packages/agent/test/global.test.ts
  packages/linker/package.json
  packages/userdive/package.json
  website/package.json
Labels: QA, bug

#429 fix(circleci) fix deploy task
  .circleci/config.yml
  package.json
Labels: QA

#430 fix(packages/agent) fix v0.x auto options
  .circleci/config.yml
  examples/built-in/package.json
  examples/linker/package.json
  examples/package.json
  examples/simple/package.json
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  packages/agent/package.json
  packages/agent/src/entrypoint/debug.ts
  packages/agent/src/entrypoint/index.ts
  packages/agent/src/global.ts
  packages/agent/test/agent.test.ts
  packages/agent/test/global.test.ts
  packages/linker/package.json
  packages/userdive/package.json
  website/package.json
Labels: QA, bug

#433 fix(crowdin) revert locale mapping
  .travis.yml
  README.md
  crowdin.yaml
Labels: in progress
