Repository userdive/agent.js, pull requests merged in 2019-01, with the labels that each got.

#936 Emit type when DOM level event occured
  packages/agent/src/browser.ts
  packages/agent/src/events.ts
  packages/agent/src/events/click.ts
  packages/agent/src/events/mousemove.ts
  packages/agent/src/events/scroll.ts
  packages/agent/src/events/touch.ts
  packages/agent/src/types.ts
  packages/agent/test/core.test.ts
  packages/agent/test/events.test.ts
  packages/agent/test/helpers/Event.ts
Labels: bug, in progress

#938 Send interactions on pagehide forcely
  packages/agent/src/agent.ts
  packages/agent/src/core.ts
  packages/agent/test/core.test.ts
Labels: enhancement, in progress

#939 Rename to interactions
  packages/agent/src/constants.ts
  packages/agent/src/core.ts
  packages/agent/src/types.ts
  packages/agent/test/agent.test.ts
  packages/agent/test/core.test.ts
Labels: enhancement, in progress

#941 upgrade webpack and ts
  package.json
  packages/agent/src/global.ts
  packages/agent/src/requests.ts
  packages/linker/test/handler.test.ts
  yarn.lock
Labels: QA

#942 send interaction with version param
  .size-limit.js
  packages/agent/src/core.ts
  packages/agent/test/core.test.ts
Labels: in progress

#940 Release 3.0.0
  CHANGELOG.md
  examples/built-in/package.json
  examples/google-optimize/package.json
  examples/kaizen-platform/package.json
  examples/optimizely-x/package.json
  examples/package.json
  examples/plugin-create/package.json
  examples/plugin-linker/package.json
  examples/simple/package.json
  examples/vwo/package.json
  examples/with-angular/package.json
  examples/with-angular1/package.json
  examples/with-google-tag-manager/package.json
  examples/with-react/package.json
  examples/with-vue/package.json
  lerna.json
  packages/agent/package.json
  packages/kaizenplatform/package.json
  packages/linker/package.json
  packages/optimizely_x/package.json
  packages/provider/package.json
  packages/userdive/package.json
  packages/vwo/package.json
  website/package.json
Labels: in progress
